package com.gov.sidesa.utils.constants

object LetterConstant {
    const val EXTRA_LETTER_CATEGORY = "EXTRA_LETTER_CATEGORY"
    const val EXTRA_LETTER_DETAIL_SUBMISSION = "EXTRA_LETTER_DETAIL_SUBMISSION"
    const val EXTRA_LETTER_DETAIL = "EXTRA_LETTER_DETAIL"
    const val EXTRA_SUBMISSION_HAS_REJECTED = "EXTRA_SUBMISSION_HAS_REJECTED"
    const val EXTRA_SUBMISSION_HAS_APPROVED = "EXTRA_SUBMISSION_HAS_APPROVED"
    const val EXTRA_LETTER_TYPE = "EXTRA_LETTER_TYPE"
    const val EXTRA_SUBMISSION_LETTER_ID = "EXTRA_SUBMISSION_LETTER_ID"
    const val EXTRA_ACTOR_APPROVAL = "EXTRA_ACTOR_APPROVAL"
    const val EXTRA_VOYAGE_ID_IN = "EXTRA_VOYAGE_ID_IN"
    const val EXTRA_VOYAGE_ID_OUT = "EXTRA_VOYAGE_ID_OUT"
    const val EXTRA_SO_NUMBER = "EXTRA_SO_NUMBER"

    const val ARG_TAB_CATEGORY = "ARG_TAB_CATEGORY"
    const val ARG_IS_SUBMISSION_PAGE = "ARG_IS_SUBMISSION_PAGE"

    const val NORMAL_STATUS = 0
    const val APPROVED_STATUS = 1
    const val REJECTED_STATUS = 2

    const val TYPE_APPROVAL_RT = "RT"
    const val TYPE_APPROVAL_RW = "RW"
    const val TYPE_APPROVAL_APPROVE = "APPROVE"
    const val TYPE_APPROVAL_WAITING_APPROVE = "WAITING_APPROVAL"
}